### ISSUE TITLE
didn't match because some of the arguments have invalid types: (Tensor, Tensor, !tuple!, !list!, bool, int, int, bool, !int!)

### ISSUE THREAD

**Issue by aishoot** [kaituoxu/TasNet#3]
Hello, thanks for sharing your code. I'm very interested in the project. But while running the project, I encountered a problem:
```bash
Training...
Traceback (most recent call last):
  File "~/TasNet/egs/wsj0/../../src/train.py", line 125, in <module>
    main(args)
  File "~/TasNet/egs/wsj0/../../src/train.py", line 119, in main
    solver.train()
  File "~/TasNet/src/solver.py", line 75, in train
    tr_avg_loss = self._run_one_epoch(epoch)
  File "~/TasNet/src/solver.py", line 174, in _run_one_epoch
    estimate_source = self.model(padded_mixture, mixture_lengths)
  File "~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "~/TasNetsrc/tasnet.py", line 36, in forward
    est_mask = self.separator(mixture_w, mixture_lengths)
  File "~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "~/TasNet/src/tasnet.py", line 155, in forward
    packed_output, hidden = self.rnn(packed_input)
  File "~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 182, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
TypeError: lstm() received an invalid combination of arguments - got (Tensor, Tensor, tuple, list, bool, int, int, bool, int), but expected one of:
 * (Tensor data, Tensor batch_sizes, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, !tuple!, !list!, bool, int, int, bool, !int!)
 * (Tensor input, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
      didn't match because some of the arguments have invalid types: (Tensor, !Tensor!, !tuple!, !list!, !bool!, int, !int!, bool, !int!)
```
请问您有遇到过这个问题吗？谢谢

**Comment by aishoot** [comment]
Solved it. Thanks.

**Comment by lingshi0606** [comment]
Excuse me, how do you solve this problem? Thanks! :)

**Comment by kaituoxu** [comment]
add bool() to self.bidirectional
