### ISSUE TITLE
您好！想问一下这个是什么错误，不太会

### ISSUE THREAD

**Issue by Evanlovea** [kaituoxu/TasNet#5]
Traceback (most recent call last):
  File "G:/speech_code/TasNet/src/train.py", line 56, in <module>
    main(ts)
  File "G:/speech_code/TasNet/src/train.py", line 52, in main
    solver.train()
  File "G:\speech_code\TasNet\src\solver.py", line 75, in train
    tr_avg_loss = self._run_one_epoch(epoch)
  File "G:\speech_code\TasNet\src\solver.py", line 176, in _run_one_epoch
    estimate_source = self.model(padded_mixture, mixture_lengths)
  File "D:\Users\15229\anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\speech_code\TasNet\src\tasnet.py", line 37, in forward
    est_mask = self.separator(mixture_w, mixture_lengths)
  File "D:\Users\15229\anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\speech_code\TasNet\src\tasnet.py", line 162, in forward
    packed_output, hidden = self.rnn(packed_input)
  File "D:\Users\15229\anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Users\15229\anaconda3\envs\speech\lib\site-packages\torch\nn\modules\rnn.py", line 664, in forward
    result = _VF.lstm(input, batch_sizes, hx, self._flat_weights, self.bias,
TypeError: lstm() received an invalid combination of arguments - got (Tensor, Tensor, tuple, list, bool, int, float, bool, int), but expected one of:
 * (Tensor data, Tensor batch_sizes, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, !tuple!, !list!, bool, int, float, bool, !int!)
 * (Tensor input, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
      didn't match because some of the arguments have invalid types: (Tensor, !Tensor!, !tuple!, !list!, !bool!, int, !float!, bool, !int!)

**Comment by Dancinglinker** [comment]
Is your problem solved, how did you solve it?

**Comment by Evanlovea** [comment]
作者说这部分没有用，后面会删掉


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月15日 13:24:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kaituoxu/TasNet] 您好！想问一下这个是什么错误，不太会 (#5)




 
Is your problem solved, how did you solve it?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SsssSunhy** [comment]
把这个
model = TasNet(args.L, args.N, args.hidden_size, args.num_layers,
                   bidirectional=args.bidirectional, nspk=args.nspk)
改成这个
model = TasNet(args.L, args.N, args.hidden_size, args.num_layers,
                   bidirectional=bool(args.bidirectional), nspk=args.nspk)
就可以用了，在注意一下torch的版本，最好不要高于1.5.0

**Comment by Evanlovea** [comment]
好的，谢谢


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月15日 20:17:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kaituoxu/TasNet] 您好！想问一下这个是什么错误，不太会 (#5)




 
把这个
 model = TasNet(args.L, args.N, args.hidden_size, args.num_layers,
 bidirectional=args.bidirectional, nspk=args.nspk)
 改成这个
 model = TasNet(args.L, args.N, args.hidden_size, args.num_layers,
 bidirectional=bool(args.bidirectional), nspk=args.nspk)
 就可以用了，在注意一下torch的版本，最好不要高于1.5.0
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
